onehungrymind/sermon-beacon

docker-compose.yml

We were on an older version of Hasura
Update from Hasura version `v1.0.0-beta.9` to `v1.0.0-beta.10`
`docker-compose.yml`
N/A

update: hasura image version

---

client/libs/theme/theme.scss

There is no global font
added font theme to angular

SB-11: Update theme and add font globally

---

README.md
docker-compose.yml

better documentation needed
update readme and docker-compose
readme and docker-compose
N/A

update: readme and docker compose

---

client/libs/searchbar/src/lib/searchbar/searchbar.component.html
client/libs/searchbar/src/lib/searchbar/searchbar.component.scss
client/libs/searchbar/src/lib/searchbar/searchbar.component.ts
client/libs/theme/_variables.scss
client/libs/ui-toolbar/src/lib/toolbar/toolbar.component.html

Issue with text overlapping filters
adjusted the styles and removed the fixed positions.
searchbar.

adjusted the styling for searchbar

---

client/apps/admin-portal/src/styles.scss

there was no main.scss in style.scss
added it back again
style.scss

feature: SB-23 fixed admin stying issue

---

client/libs/core-state/src/lib/index.ts

Missing some the Speaker reducer import in the core-state/src/lib/index.ts file
Added the needed import
Core-State lib
N/A

SB-14: ngrx speakers fix 

---

client/libs/core-state/src/index.ts
client/libs/core-state/src/lib/core-state.module.ts
client/libs/core-state/src/lib/index.ts
client/libs/core-state/src/lib/tags/tags.actions.ts
client/libs/core-state/src/lib/tags/tags.effects.ts
client/libs/core-state/src/lib/tags/tags.facade.ts
client/libs/core-state/src/lib/tags/tags.reducer.ts
client/libs/core-state/src/lib/tags/tags.selectors.ts
client/libs/core-state/src/lib/tags/tests/tags.effects.spec.ts
client/libs/core-state/src/lib/tags/tests/tags.facade.spec.ts
client/libs/core-state/src/lib/tags/tests/tags.reducer.spec.ts
client/libs/core-state/src/lib/tags/tests/tags.selectors.spec.ts
client/package.json

NgRx Tags Setup
NgRx Tags Setup
Core-State
N/A

SB-14: Tags NgRx feature

---

README.md

Problem, deleted README
Added README back
N/A
N/A

fix: added README back in

---

client/libs/core-state/src/index.ts
client/libs/core-state/src/lib/core-state.module.ts
client/libs/core-state/src/lib/index.ts
client/libs/core-state/src/lib/media-types/media-types.actions.ts
client/libs/core-state/src/lib/media-types/media-types.effects.ts
client/libs/core-state/src/lib/media-types/media-types.facade.ts
client/libs/core-state/src/lib/media-types/media-types.reducer.ts
client/libs/core-state/src/lib/media-types/media-types.selectors.ts
client/libs/core-state/src/lib/media-types/tests/media-types.effects.spec.ts
client/libs/core-state/src/lib/media-types/tests/media-types.facade.spec.ts
client/libs/core-state/src/lib/media-types/tests/media-types.reducer.spec.ts
client/libs/core-state/src/lib/media-types/tests/media-types.selectors.spec.ts
client/libs/core-state/src/lib/media/media.facade.ts
client/libs/core-state/src/lib/tags/tags.facade.ts

New NgRx feature, MediaTypes
Implemented new MediaTypes NgRx feature
Core-State
N/A

SB-14: feat: setup MediaTypes feature

---

.github/workflows/stage-deployment.yaml

update actions to use yarn and run ng lint
update deployment yaml file
Deployment yaml file
N/A

update: deploy yml

---

.github/workflows/stage-deployment.yaml
client/package.json

Update deploy yml

---

client/libs/core-state/src/lib/media-types/media-types.actions.ts
client/libs/core-state/src/lib/media-types/media-types.effects.ts
client/libs/core-state/src/lib/media-types/media-types.facade.ts
client/libs/core-state/src/lib/media-types/media-types.reducer.ts
client/libs/core-state/src/lib/media-types/media-types.selectors.ts
client/libs/core-state/src/lib/media/media.actions.ts
client/libs/core-state/src/lib/media/media.effects.ts
client/libs/core-state/src/lib/media/media.facade.ts
client/libs/core-state/src/lib/media/media.reducer.ts
client/libs/core-state/src/lib/media/media.selectors.ts
client/libs/core-state/src/lib/sermons/sermons.actions.ts
client/libs/core-state/src/lib/sermons/sermons.effects.ts
client/libs/core-state/src/lib/sermons/sermons.facade.ts
client/libs/core-state/src/lib/sermons/sermons.reducer.ts
client/libs/core-state/src/lib/sermons/sermons.selectors.ts
client/libs/core-state/src/lib/speakers/speakers.actions.ts
client/libs/core-state/src/lib/speakers/speakers.effects.ts
client/libs/core-state/src/lib/speakers/speakers.facade.ts
client/libs/core-state/src/lib/speakers/speakers.reducer.ts
client/libs/core-state/src/lib/speakers/speakers.selectors.ts
client/libs/core-state/src/lib/tags/tags.actions.ts
client/libs/core-state/src/lib/tags/tags.effects.ts
client/libs/core-state/src/lib/tags/tags.facade.ts
client/libs/core-state/src/lib/tags/tags.reducer.ts
client/libs/core-state/src/lib/tags/tags.selectors.ts

The naming of the actions, and the actions strings. The inconsistency in naming throughout the NGRX reducer features, like the selectId property on initialState. The names of the Observables in the NGRX feature Facades, the naming of the selectors
Refactored, so that there's consistency across features
Core-State
N/A

SB-41: NgRx features refactor

---

client/libs/core-state/src/lib/media-types/media-types.effects.ts
client/libs/core-state/src/lib/media/media.effects.ts
client/libs/core-state/src/lib/sermons/sermons.effects.ts
client/libs/core-state/src/lib/speakers/speakers.effects.ts
client/libs/core-state/src/lib/tags/tags.effects.ts
client/libs/ui-libraries/src/lib/ui-modal/ui-modal.component.html
client/libs/ui-libraries/src/lib/ui-modal/ui-modal.component.ts
client/libs/ui-libraries/src/lib/ui-services/dialog/dialog.service.ts

Delete effects weren't actually working
call the delete service

Update ngrx deletion

---

client/libs/core-data/src/lib/sermons/sermon.model.ts
client/libs/core-data/src/lib/speakers/speaker.model.ts
client/libs/core-data/src/lib/speakers/speakers.graphql.ts
client/libs/core-data/src/lib/speakers/speakers.service.ts
client/libs/core-state/src/lib/speakers/speakers.actions.ts
client/libs/core-state/src/lib/speakers/speakers.effects.ts
client/libs/core-state/src/lib/speakers/speakers.facade.ts
client/libs/core-state/src/lib/speakers/speakers.reducer.ts
client/libs/sermons/src/lib/sermons-dialog/sermons-details/sermons-details.component.ts
client/libs/sermons/src/lib/sermons/sermons.component.ts

Sermons table was not showing the speakers
update table and ngrx features to get sermon speakers
sermon table/ngrx feature

SB-43: update sermon table

---

client/libs/core-data/src/lib/speakers/speakers.graphql.ts

there were some issues with the fragments here
update fragment names
speakers.graphql.ts
N/A

fix: speakers fragment

---

client/libs/core-data/src/lib/core-data.module.ts
client/libs/core-data/src/lib/sermon-speakers/sermon-speaker.model.ts
client/libs/core-data/src/lib/sermon-speakers/sermon-speakers.graphql.ts
client/libs/core-data/src/lib/sermon-speakers/sermon-speakers.service.ts
client/libs/core-data/src/lib/sermons/sermons.graphql.ts
client/libs/core-data/src/lib/sermons/sermons.service.ts
client/libs/core-data/src/lib/speakers/speaker.model.ts
client/libs/core-state/src/lib/index.ts
client/libs/core-state/src/lib/sermon-speakers/sermon-speakers.actions.ts
client/libs/core-state/src/lib/sermon-speakers/sermon-speakers.effects.ts
client/libs/core-state/src/lib/sermon-speakers/sermon-speakers.facade.ts
client/libs/core-state/src/lib/sermon-speakers/sermon-speakers.reducer.ts
client/libs/core-state/src/lib/sermons/sermons.actions.ts
client/libs/core-state/src/lib/sermons/sermons.effects.ts
client/libs/core-state/src/lib/sermons/sermons.facade.ts
client/libs/core-state/src/lib/sermons/sermons.reducer.ts
client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.html
client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.ts
client/libs/sermons/src/lib/sermons/sermons.component.html
client/libs/sermons/src/lib/sermons/sermons.component.ts
client/libs/ui-libraries/src/lib/searchbar/searchbar.component.ts

sermons speakers were not properly displaying on the sermons column
update feature to grab sermon-speakers from hasura
sermons component/ngrx
also updated search and is now working
> NOTE: SB-53 has been fixed as well

SB-48: sermon speakers column

---

client/apps/admin-portal/src/app/sermon-view/sermon-view.component.html
client/apps/admin-portal/src/app/sermon-view/sermon-view.component.scss
client/apps/admin-portal/src/app/sermon-view/sermon-view.component.ts
client/libs/ui-libraries/src/lib/no-video/no-video.component.html
client/libs/ui-libraries/src/lib/no-video/no-video.component.ts

Spell out and show all users
show all users instead of just one with an ellipsis
sermon-view.component
WEB:
MOBILE:

SB-52: speakers list

---

client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.html

sermons needed cursor pointer to let user better know that they can click on it
add cursor pointer to the sermon items
sermon list

SB-46: add cursor pointer to sermon list

---

client/apps/admin-portal/src/app/sermon-view/sermon-view.component.html
client/yarn.lock

Media Buttons needed alignment
Aligned media buttons
Video-View

SB-57: action buttons

---

client/apps/admin-portal/src/app/sermon-view/sermon-view.component.html
client/apps/admin-portal/src/app/sermon-view/sermon-view.component.scss
client/yarn.lock

Align Tags vertically on mobile
Align Tags vertically on mobile
Sermon View 

SB-58: video tags

---

client/apps/admin-portal/src/environments/environment.prod.ts
client/apps/admin-portal/src/environments/environment.ts
client/libs/core-data/src/index.ts
client/libs/core-data/src/lib/auth/auth.service.ts
client/libs/core-data/src/lib/auth/token.interceptor.spec.ts
client/libs/core-data/src/lib/auth/token.interceptor.ts
client/libs/core-data/src/lib/core-data.module.ts

The headers weren't always being set properly especially on initial login
Switch from `createApollo` header appending to a global token interceptor
apollo headers
N/A

SB-64: fix headers issue

---

client/libs/sermons/src/lib/sermons-dialog/sermons-dialog.component.html
client/libs/sermons/src/lib/sermons-dialog/sermons-dialog.component.ts
client/libs/sermons/src/lib/sermons-dialog/sermons-media/sermons-media.component.html
client/libs/sermons/src/lib/sermons-dialog/sermons-media/sermons-media.component.ts

We were not able to remove media groups if needed
add the ability to remove media groups
sermons-dialog component

SB-66: ability to remove mediagroups

---

client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.ts
client/libs/sermons/src/lib/sermons/sermons.component.html
client/libs/sermons/src/lib/sermons/sermons.component.ts

nothing was displaying when searching and no results were returned
created a default row so that user knows there is no search results
sermons table

refactor: create default search row when no results found

---

client/libs/core-data/src/lib/core-data.module.ts
client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.html
client/libs/sermons/src/lib/sermons/sermon-table/sermon-table.component.scss
client/libs/sermons/src/lib/sermons/sermons.component.html
client/libs/ui-libraries/src/lib/searchbar/searchbar.component.html
client/libs/ui-libraries/src/lib/searchbar/searchbar.component.scss
client/libs/ui-libraries/src/lib/ui-table/ui-table.component.scss

Tables and searchbar weren't mobile responsive
Made them mobile responsive.
Sermon-Table, ui-table, searchbar components

Sb-59: table mobile view

---

client/libs/core-data/src/lib/sermon-speakers/sermon-speakers.service.ts

The current date searched was not being displayed.
round the query up a day since for some reason moment is rounding down.
sermon-speakers.service

SB-62: fix date query

---

client/libs/sermons/src/lib/sermons-dialog/sermons-dialog.component.html

We were hiding the submit button until the very end
include the submit button on all sections of the form
sermons dialog

SB-69: submit button
